# 2. Frame Extraction

In [38]:
import cv2
import os

def extract_frames(video_path, output_dir, frame_rate=1):
    # Create output directory if it doesn't exist
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    # Open the video file
    video = cv2.VideoCapture(video_path)
    
    if not video.isOpened():
        print(f"Error: Could not open video file {video_path}")
        return
    
    # Get video properties
    fps = video.get(cv2.CAP_PROP_FPS)
    total_frames = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
    duration = total_frames / fps
    
    print(f"Video FPS: {fps}")
    print(f"Total frames: {total_frames}")
    print(f"Duration: {duration:.2f} seconds")
    
    # Initialize frame counter
    count = 0
    frame_count = 0
    
    # Read until video is completed
    while True:
        ret, frame = video.read()
        
        # Break the loop if we have reached the end of the video
        if not ret:
            break
        
        # Save frame at the specified interval
        if count % 1 == 0:
            frame_filename = os.path.join(output_dir, f"frame_{frame_count:04d}.jpg")
            cv2.imwrite(frame_filename, frame)
            print(f"Extracted: {frame_filename}")
            frame_count += 1
        
        count += 1
    
    # Release the video capture object
    video.release()
    
    print(f"Extraction complete. {frame_count} frames extracted to {output_dir}")

def get_file_paths():
    file_paths = []

    for root, dirs, files in os.walk("videos"):
        for file in files:
            file_path = os.path.join(root, file)
            file_paths.append(file_path)

    return file_paths

if not os.path.isdir('frames'): # If it exists, it was done already so do not run
    file_paths = get_file_paths()

    for file_path in file_paths:
        extract_frames(file_path, os.path.join("frames", os.path.basename(file_path)))
else :
    print("Frames had already been extracted, skipping...")

Frames had already been extracted, skipping...


# 3. Feature Detection and Description

In [39]:
import time

#feature detection using ORB, SIFT, and BRISK
def load_images_from_all_videos(base_folder, max_images_per_video=10):
    all_images = []
    video_folders = sorted(os.listdir(base_folder))

    image_extensions = ['.jpg', '.jpeg', '.png', '.bmp']

    for video_folder in video_folders:
        full_path = os.path.join(base_folder, video_folder)
        if not os.path.isdir(full_path):
            continue  # skip non-folder entries

        image_filenames = sorted(os.listdir(full_path))
        image_files = [f for f in image_filenames if os.path.splitext(f)[1].lower() in image_extensions]

        for filename in image_files[:max_images_per_video]:
            img_path = os.path.join(full_path, filename)
            img_color = cv2.imread(img_path)
            if img_color is None:
                print(f"Warning: Couldn't read {img_path}")
                continue
            img_gray = cv2.cvtColor(img_color, cv2.COLOR_BGR2GRAY)
            all_images.append((video_folder + "/" + filename, img_color, img_gray))

    return all_images

#detect features using ORB, SIFT, and BRISK
def detect_features(detector, images, use_gray=True):
    results = []
    for filename, img_color, img_gray in images:
        img = img_gray if use_gray else img_color
        start_time = time.time()
        keypoints, descriptors = detector.detectAndCompute(img, None)
        time_taken = time.time() - start_time
        results.append({
            'filename': filename,
            'image': img_color,
            'keypoints': keypoints,
            'descriptors': descriptors,
            'time': time_taken
        })
    return results

#draw keypoints on images
def draw_keypoints(results, alg_name, output_dir="output_keypoints"):
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    for res in results:
        img_with_kp = cv2.drawKeypoints(res['image'], res['keypoints'], None, color=(0, 255, 0))
        out_path = os.path.join(output_dir, f"{alg_name}_{res['filename'].replace('/', '_')}")
        cv2.imwrite(out_path, img_with_kp)

#analyze results
def analysis(results, alg_name):
    print(f"\n - - {alg_name} - -")
    total_kps = 0
    total_time = 0

    #print summary of results
    for res in results:
        print(f"{res['filename']}: {len(res['keypoints'])} keypoints in {res['time']:.4f}s")
        total_kps += len(res['keypoints'])
        total_time += res['time']
    if len(results) > 0:
        avg_kps = total_kps / len(results)
        avg_time = total_time / len(results)
        print(f"Average keypoints: {avg_kps:.2f} | Average Time: {avg_time:.2f}s")
    else:
        print("No images were processed.")

frame_dir = "frames"  #path to frames
images = load_images_from_all_videos(frame_dir, max_images_per_video=10)

if not images:
    print("No images found in any of the video subfolders.")
    exit()

#initialize detectors
orb = cv2.ORB_create(nfeatures=1000)
sift = cv2.SIFT_create()
brisk = cv2.BRISK_create()

#detect features
orb_results = detect_features(orb, images)
sift_results = detect_features(sift, images)
brisk_results = detect_features(brisk, images)

#save keypoint visualizations
if not os.path.exists("output_keypoints"): # Exists so no need to save
    draw_keypoints(orb_results, "ORB")
    draw_keypoints(sift_results, "SIFT")
    draw_keypoints(brisk_results, "BRISK")

#print comparison summary
analysis(orb_results, "ORB")
analysis(sift_results, "SIFT")
analysis(brisk_results, "BRISK")


 - - ORB - -
Vid1.mp4/frame_0000.jpg: 976 keypoints in 0.0065s
Vid1.mp4/frame_0001.jpg: 977 keypoints in 0.0059s
Vid1.mp4/frame_0002.jpg: 976 keypoints in 0.0060s
Vid1.mp4/frame_0003.jpg: 976 keypoints in 0.0057s
Vid1.mp4/frame_0004.jpg: 977 keypoints in 0.0055s
Vid1.mp4/frame_0005.jpg: 983 keypoints in 0.0056s
Vid1.mp4/frame_0006.jpg: 985 keypoints in 0.0060s
Vid1.mp4/frame_0007.jpg: 985 keypoints in 0.0056s
Vid1.mp4/frame_0008.jpg: 980 keypoints in 0.0059s
Vid1.mp4/frame_0009.jpg: 980 keypoints in 0.0060s
Vid2.mp4/frame_0000.jpg: 947 keypoints in 0.0054s
Vid2.mp4/frame_0001.jpg: 954 keypoints in 0.0056s
Vid2.mp4/frame_0002.jpg: 948 keypoints in 0.0057s
Vid2.mp4/frame_0003.jpg: 957 keypoints in 0.0055s
Vid2.mp4/frame_0004.jpg: 952 keypoints in 0.0060s
Vid2.mp4/frame_0005.jpg: 960 keypoints in 0.0056s
Vid2.mp4/frame_0006.jpg: 951 keypoints in 0.0057s
Vid2.mp4/frame_0007.jpg: 946 keypoints in 0.0061s
Vid2.mp4/frame_0008.jpg: 949 keypoints in 0.0055s
Vid2.mp4/frame_0009.jpg: 953 keypoin

# 4/5. Feature Matching and Outlier Rejection + Fundamental Matrix Computation

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

#load images from all videos
def load_image_pairs(base_folder, step=1, max_pairs_per_video=3):
    pairs = []
    video_folders = sorted(os.listdir(base_folder))

    #filter out non-directory entries
    for video_folder in video_folders:
        folder_path = os.path.join(base_folder, video_folder)
        if not os.path.isdir(folder_path):
            continue

        filenames = sorted([f for f in os.listdir(folder_path) if f.endswith((".jpg", ".jpeg", ".png"))])
        num_pairs = min(len(filenames) - step, max_pairs_per_video)

        for i in range(num_pairs):
            img1_path = os.path.join(folder_path, filenames[i])
            img2_path = os.path.join(folder_path, filenames[i + step])

            img1 = cv2.imread(img1_path, cv2.IMREAD_GRAYSCALE)
            img2 = cv2.imread(img2_path, cv2.IMREAD_GRAYSCALE)

            if img1 is not None and img2 is not None:
                pairs.append((f"{video_folder}/{filenames[i]}", f"{video_folder}/{filenames[i+step]}", img1, img2))
    return pairs

#get feature detector
def get_detector(name="SIFT"):
    if name == "ORB":
        return cv2.ORB_create(nfeatures=1000)
    elif name == "BRISK":
        return cv2.BRISK_create()
    else:
        return cv2.SIFT_create()

#get matcher based on descriptor type
def get_matcher(desc_type):
    if desc_type == "float":
        index_params = dict(algorithm=1, trees=5)
        search_params = dict(checks=50)
        return cv2.FlannBasedMatcher(index_params, search_params)
    else:
        return cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=True)

#match features between two images
def match_features(detector, img1, img2):
    kp1, des1 = detector.detectAndCompute(img1, None)
    kp2, des2 = detector.detectAndCompute(img2, None)

    if des1 is None or des2 is None:
        return kp1, kp2, []

    #check descriptor type
    desc_type = "float" if des1.dtype == np.float32 else "binary"
    matcher = get_matcher(desc_type)

    if desc_type == "float":
        matches = matcher.knnMatch(des1, des2, k=2)
        good_matches = []
        for m, n in matches:
            if m.distance < 0.75 * n.distance:
                good_matches.append(m)
    else:
        matches = matcher.match(des1, des2)
        good_matches = sorted(matches, key=lambda x: x.distance)

    return kp1, kp2, good_matches

#ransac filter to remove outliers
def ransac_filter(kp1, kp2, matches):
    if len(matches) < 8:
        return [], None

    #extract location of good matches
    pts1 = np.float32([kp1[m.queryIdx].pt for m in matches])
    pts2 = np.float32([kp2[m.trainIdx].pt for m in matches])

    F, mask = cv2.findFundamentalMat(pts1, pts2, cv2.RANSAC)
    inliers = [m for i, m in enumerate(matches) if mask[i]]

    return inliers, F

#draw matches between two images
def draw_matches(img1, kp1, img2, kp2, matches, title, out_folder="output_matches", filename_prefix="match"):
    if not os.path.exists(out_folder):
        os.makedirs(out_folder)

    #draw matches
    matched_img = cv2.drawMatches(img1, kp1, img2, kp2, matches, None, flags=cv2.DRAW_MATCHES_FLAGS_NOT_DRAW_SINGLE_POINTS)

    plt.figure(figsize=(12, 6))
    plt.imshow(matched_img, cmap='gray')
    plt.title(title)
    plt.axis('off')

    #save figure with title in filename
    safe_title = title.replace(" ", "_").lower()
    out_path = os.path.join(out_folder, f"{filename_prefix}_{safe_title}.png")
    plt.savefig(out_path, bbox_inches='tight')
    plt.close()


#set parameters
frame_dir = "frames"
detector_name = "SIFT"
detector = get_detector(detector_name)

pairs = load_image_pairs(frame_dir, step=1, max_pairs_per_video=3)

#check if pairs are loaded
for fname1, fname2, img1, img2 in pairs:
    print(f"\nProcessing pair: {fname1} & {fname2}")
    kp1, kp2, matches = match_features(detector, img1, img2)

    print(f"Total matches before RANSAC: {len(matches)}")

    draw_matches(img1, kp1, img2, kp2, matches, title="Before RANSAC", filename_prefix=f"{fname1.replace('/', '_')}_vs_{fname2.replace('/', '_')}")

    inliers, F = ransac_filter(kp1, kp2, matches)
    print(f"Matches after RANSAC: {len(inliers)}")
    draw_matches(img1, kp1, img2, kp2, inliers, title="After RANSAC", filename_prefix=f"{fname1.replace('/', '_')}_vs_{fname2.replace('/', '_')}")


Processing pair: Vid1.mp4/frame_0000.jpg & Vid1.mp4/frame_0001.jpg
Total matches before RANSAC: 241
Matches after RANSAC: 231

Processing pair: Vid1.mp4/frame_0001.jpg & Vid1.mp4/frame_0002.jpg
Total matches before RANSAC: 230
Matches after RANSAC: 226

Processing pair: Vid1.mp4/frame_0002.jpg & Vid1.mp4/frame_0003.jpg
Total matches before RANSAC: 247
Matches after RANSAC: 241

Processing pair: Vid2.mp4/frame_0000.jpg & Vid2.mp4/frame_0001.jpg
Total matches before RANSAC: 154
Matches after RANSAC: 150

Processing pair: Vid2.mp4/frame_0001.jpg & Vid2.mp4/frame_0002.jpg
Total matches before RANSAC: 156
Matches after RANSAC: 151

Processing pair: Vid2.mp4/frame_0002.jpg & Vid2.mp4/frame_0003.jpg
Total matches before RANSAC: 158
Matches after RANSAC: 152

Processing pair: Vid3.mp4/frame_0000.jpg & Vid3.mp4/frame_0001.jpg
Total matches before RANSAC: 246
Matches after RANSAC: 243

Processing pair: Vid3.mp4/frame_0001.jpg & Vid3.mp4/frame_0002.jpg
Total matches before RANSAC: 262
Matches af

As required by the assignment, this section explains the underlying calculations involved in computing the fundamental matrix and clarifies the distinction between calibrated and uncalibrated cameras.

#### 5a. Understanding Underlying Calculations for Fundamental Matrix Computation

When computing the fundamental matrix ($F$) using a function like OpenCV's `cv.findFundamentalMat()`, the process relies on the epipolar constraint, which states that for any pair of corresponding points $p_1$ in the first image and $p_2$ in the second image, the following relationship holds:

$$p_2^T F p_1 = 0$$

Here, $p_1$ and $p_2$ are the homogeneous coordinates of the points. The fundamental matrix is a $3 \times 3$ matrix that encapsulates the epipolar geometry between the two uncalibrated views.

The fundamental matrix has 9 elements but is determined up to a scale factor, giving 8 degrees of freedom. Additionally, it must satisfy the rank constraint $det(F) = 0$.

A common method for estimating the fundamental matrix is the **Eight-Point Algorithm**. This algorithm uses at least 8 pairs of corresponding points to set up a system of linear equations in the elements of $F$. Each corresponding point pair $(p_{1i}, p_{2i})$ contributes one linear equation based on the epipolar constraint. If we stack the elements of $F$ into a vector $f$, we get a system of equations $Af = 0$, where $A$ is a matrix derived from the point coordinates. This system can be solved for $f$ (and thus $F$) using methods like Singular Value Decomposition (SVD).

The linear estimate of $F$ from the 8-point algorithm may not satisfy the rank-2 constraint. To enforce this, SVD is typically applied to the estimated $F = U \Sigma V^T$. We then set the smallest singular value in $\Sigma$ to zero to produce $\Sigma'$, resulting in the rank-2 fundamental matrix $F' = U \Sigma' V^T$.

In the presence of outliers (incorrect matches), a robust estimation method like **RANSAC (Random Sample Consensus)** is employed. When you use `cv.findFundamentalMat()` with the `cv2.RANSAC` method, OpenCV is internally implementing a RANSAC-based approach. RANSAC iteratively:
1.  Selects a minimal set of 8 point correspondences.
2.  Computes a candidate fundamental matrix using these points.
3.  Counts how many of the *remaining* points are consistent with this matrix (inliers).
4.  Repeats this process many times and chooses the matrix with the largest number of inliers.
5.  Optionally, re-estimates the matrix using all identified inliers.

This robust estimation is crucial for obtaining an accurate fundamental matrix from noisy real-world data.

#### 5b. Difference Between Calibrated and Uncalibrated Cameras

The choice of computing the essential matrix ($E$) or the fundamental matrix ($F$) depends on whether your cameras are calibrated.

* **Uncalibrated Cameras:**
    * **Definition:** Cameras for which the intrinsic parameters (focal length, principal point, distortion coefficients) are **unknown**.
    * **Matrix:** The **Fundamental Matrix ($F$)** is used.
    * **Coordinates:** $F$ relates corresponding points in **image coordinates (pixels)**.
    * **Purpose:** Describes the epipolar geometry (relationship between points and epipolar lines) in the image plane. It can be used to verify point correspondences and find epipolar lines.
    * **Limitation:** Without knowing the intrinsic parameters, $F$ does not encode metric information about the scene or the cameras' 3D motion.

* **Calibrated Cameras:**
    * **Definition:** Cameras for which the intrinsic parameters are **known** (usually determined through a camera calibration procedure).
    * **Matrix:** The **Essential Matrix ($E$)** is used.
    * **Coordinates:** $E$ relates corresponding points in **normalized image coordinates**. These coordinates are obtained by removing the effect of intrinsic parameters (e.g., by multiplying image coordinates by the inverse of the camera intrinsic matrix, $K^{-1}$).
    * **Relationship:** The essential matrix is related to the fundamental matrix by the camera intrinsic matrices $K_1$ and $K_2$: $E = K_2^T F K_1$.
    * **Purpose:** Describes the epipolar geometry in a normalized coordinate system and crucially encodes the **relative rotation and translation** between the two camera views.
    * **Advantage:** Knowing the intrinsic parameters and having the essential matrix allows for the recovery of the camera's relative 3D pose and enables metric 3D reconstruction of the scene.

In the context of this assignment, the videos were taken using an uncalibrated mobile phone camera. Therefore the fundamental matrix was computed and not the essential matrix.

6. Camera Position Estimation

In [41]:

pixel_focal_length = 4500
image_width = 478
image_height = 850

# Principal point assumed at the image center
principal_point_x = image_width / 2
principal_point_y = image_height / 2

camera_matrix = np.array([[pixel_focal_length, 0, principal_point_x], [0, pixel_focal_length, principal_point_y], [0, 0, 1]], dtype=np.float32)

print("Using Placeholder Camera Matrix:")
print(camera_matrix)


# Extract points from inlier matches
pts1 = np.float32([kp1[m.queryIdx].pt for m in inliers]).reshape(-1, 1, 2)
pts2 = np.float32([kp2[m.trainIdx].pt for m in inliers]).reshape(-1, 1, 2)


# Estimate camera pose using recoverPose
# Note: Using F with a placeholder K provides scaled translation.
ret, R, t, mask = cv2.recoverPose(F, pts1, pts2, camera_matrix)

print("\n--- Camera Pose Estimation Results ---")
print(f"Number of points successfully reconstructed in front of both cameras: {ret}")
print("\nEstimated Rotation Matrix (R):")
print(R)
print("\nEstimated Translation Vector (t):")
print(t)

Using Placeholder Camera Matrix:
[[4.50e+03 0.00e+00 2.39e+02]
 [0.00e+00 4.50e+03 4.25e+02]
 [0.00e+00 0.00e+00 1.00e+00]]

--- Camera Pose Estimation Results ---
Number of points successfully reconstructed in front of both cameras: 0

Estimated Rotation Matrix (R):
[[ 0.99840873 -0.00327113 -0.05629657]
 [ 0.00609101  0.99873107  0.04999145]
 [ 0.0560616  -0.0502548   0.99716175]]

Estimated Translation Vector (t):
[[-0.66374949]
 [-0.74795118]
 [-0.00237406]]
